targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
            
      json_serializable:
        options:
          create_to_json: true
          field_rename: snake

      freezed:
        options:
          map: true
          when: true
