name: core
description: core mobile app package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  common: 
    path: packages/common
  locale: 
    path: packages/locale

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  go_router: ^14.1.4
  provider: ^6.1.2
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  lint: ^2.3.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - packages/common/assets/icons/