name: common
description: "Common package."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # local packages
  locale:
    path: ../locale

  # owned packages
  smart_flutter_utils: ^1.0.1+3
  smart_flutter_widgets: ^1.0.0+3
  smart_http: ^1.0.1

  # third-party packages
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: ^8.1.4
  go_router: ^14.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  mocktail: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/